image: docker:19-git

services:
  - docker:dind

stages:
  - build
  - push

docker-image:
  image: docker:19-git
  # before_script:
  # - apk add --update --no-cache git
  services:
    - docker:dind
  stage: build
  # before_script:
  # - apk add --update --no-cache git
  script:
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin 
    - docker build -t $JAVA_REPO_NAME .
    - docker push $JAVA_REPO_NAME
